import vectors as vec

#vec1 = vec.Vector2D(9,5)
#vec2 = vec.Vector2D(7,-7.)
#veccomprod = vec.Vector2D(1,1)
#vecextend = vec.Vector2D(-1,0)
#print(vec1)

#print(vec1.module)
#veccomprod.scalar_prod()
#print(veccomprod)
#vecsuma = vec.Vector2D.sum(vec1,vec2)
#print(vecsuma)
#vecrest = vec.Vector2D.subtrack(vec1,vec2)
#print(vecrest)
#vecprond = vec.Vector2D.dot_product(vec1,vec2)
#print(vecprond)
#dist2D = vec.Vector2D.distance(vec1,vec2)
#print(dist2D)
#vec2Dto3D = vecextend.extend_to_3D()
#print(vec2Dto3D)

vec1 = vec.Vector3D(4,5,9)
vec2 = vec.Vector3D(7,-7.,-8)
#veccomprod = vec.Vector3D(1,1,78)

#print(vec1.module)
#veccomprod.scalar_prod()
#print(veccomprod)
#vecsuma = vec.Vector3D.sum(vec1,vec2)
#print(vecsuma)
#vecrest = vec.Vector3D.subtrack(vec1,vec2)
#print(vecrest)
#vecprond = vec.Vector3D.dot_product(vec1,vec2)
#print(vecprond)
veczero = vec.Vector3D.zero()
print(veczero)
vechori = vec.Vector3D.horizontal()
print(vechori)
vecver = vec.Vector3D.vertical()
print(vecver)
vecfor = vec.Vector3D.forward()
print(vecfor)